### PR TITLE
Fix build error on macOS/OS X

### PR DESCRIPTION
**Pull request by clobber**
I was experimenting with building CG using the CMake setup and this was a compile error I encountered.

### CODE REVIEW

**Comment by gerstrong** [comment]
Nice, thanks!

**Comment by clobber** [comment]
By the way, I figure I should probably note a few other things:

* The app can be successfully compiled on macOS using the CMake setup if the `-lGL` linker flag is removed from both the autogenerated link.txt files - the already included `-framework OpenGL` is all that is needed on Mac. This might be because there is not a macOS/OS X target? Mine defaulted to 'Linux'.

* CGeniusEXE crashes when `OpenGL = true` in cgenius.cfg so I had to set to false. Here's the log (which doesn't look too helpful, so it will need to be debugged in Xcode): https://gist.github.com/anonymous/7f496c86258bf5ecc810b03295c29fcf

* The default UI size makes everything really hard to navigate from the start. Suggesting to default to the next size up, such as 800x600.

Anyway, here's it running:

mqesp16

nnyfo9c

**Comment by clobber** [comment]
Update:

I ran the binary on my new machine with macOS 10.12.5 installed and `OpenGL = true` works fine. Maybe there is a problem on 10.11.

**Comment by gerstrong** [comment]
I fixed some stuff months ago so it can run under MacOS. I really did that using virtualized equipment and it didn't run that well. At least it got built, what was my intention anyways.

I really would like to support MacOS but I really lack of time. Even Tom Hall asked about a year ago for an version. So if you can create some bundle, in case you want of course, you really would make him happy and me as well. You have my full support for that matter. Also putting you into the credits is no  issue. 

Now to your suggestions, thanks you very much fixing stuff that was needed to be fixed. I haven't been touching this for a while:

- We can force to use OpenGL. It is the better choice and well supported by MacOS anyways.
- About the flag I think the "framework" is the better choice in that regard
- There have been complains about the default Window Size. We can choose a larger one, no problem.

Also remember this is not yet the release I'm planning. I'm fixing some bugs and improving. So if you find obvious errors and you can fix I'm fine with that. It helps the product getting better :-)

**Comment by pizza2004** [comment]
Oh hey guys!  If someone can get the Xcode project working again I'd be happy to maintain the macOS port again.  Sorry for disappearing for a while.  I came back and tried to get it working again a few months or maybe a year back but I couldn't figure it out so I just ended up leaving it alone again.

**Comment by clobber** [comment]
@gerstrong I think you may have misunderstood what I meant regarding OpenGL:

* On my Mid-2009 MBP with NVIDIA GeForce 9400M running OS X 10.11, CG **crashes** with opengl=true so I had to set it to false (here's the [crash log](https://gist.github.com/anonymous/7f496c86258bf5ecc810b03295c29fcf)).
* But on my new MBP running macOS 10.12, CG runs fine with opengl=true.

So there may be a problem with the OpenGL render mode on 10.11 or that particular GPU.

Anyway, attached here is a redistributable build from the latest source (bbf7556) that is properly packaged with the required dylibs and should at least run on macOS 10.12. Tom Hall or anyone else can feel free to use it. Just for some background, I used the CMake script to compile the binary after installing all dependencies with homebrew, edited the link.txt files to remove the `-lGL` linker flag, manually built an app bundle using an older CG one as a base and finally packaged up all the dylibs using [macpack](https://github.com/chearon/macpack) which automates the process of `otool -L` and `install_name_tool`.

**Download:** [Commander Genius.zip](https://github.com/gerstrong/Commander-Genius/files/1065157/Commander.Genius.zip)

@pizza2004 Honestly, I feel that maintaining an Xcode project is an unnecessary burden at this point especially where matters of compatibility are concerned. Ever since Apple's move to a unitary SDK model, it is increasingly harder to target older versions of macOS/OS X using Xcode and the latest SDK. With a few slight changes to the CMake script, compiling Commander Genius for Mac can be fixed and we can automate nearly the rest of the process for creating a redistributable app bundle.

**Comment by gerstrong** [comment]
> On my Mid-2009 MBP with NVIDIA GeForce 9400M running OS X 10.11, CG crashes with opengl=true so I had to set it to false (here's the crash log).

Have you tried different resolutions? It seems that the hardware does not support mode. I'll take another look into code at this position. You can configure that in the CGenius.cfg file.

It seems to be running well with SDL2. I think we can leave OpenGL for all systems out and all good for now. SDL2 supports hardware accelerated 2D anyways and native Quartz is used.

@pizza2004 I think that's a good idea because CMake is what is mainly used and I better changes for updating files and code which effects the build process of MacOS also in a positive way. If you want to maintain it, no matter it would be nice. Updating the XCode will be difficult for me since I lack of time and resources for doing so.

@clobber Thanks for tips and patches. I'll consider removing `-lGL` in CMakeList.txt for Apple system and it should not appear anymore in the link.txt file. Does that make sense? Not sure where `link.txt` comes from. Still I can take a look.

**Comment by gerstrong** [comment]
Hi, I have uploaded the ZIP-File: [CG Downloads](http://clonekeenplus.sourceforge.net/download/)

Thanks again for your collaboration! I will write to Tom Hall, put some news to PCKF and also keep you informed.

**Comment by clobber** [comment]
>Have you tried different resolutions?

On 10.11, I've tried resolutions of 640x480 and 800x600 which are both crashing with opengl for me.


Regarding CMake:

So the the trouble with the CMake script is here https://github.com/gerstrong/Commander-Genius/blob/master/src/CMakeLists.txt#L18-L19 where it defaults to the Linux target if you did not select Windows which then sets the `-lGL` linker flag here https://github.com/gerstrong/Commander-Genius/blob/master/src/CMakeLists.txt#L249-L250 (the one written to link.txt) which is incorrect if you are compiling on a Mac, causing build failure. `-lGL` should only be set for LINUX targets, obviously.

As far as I know, you don't need to default to a target using CMake because it should be smart enough to at least autodetect WIN32, LINUX or APPLE targets. So the default fallback to Linux should be removed. That will correct part of the problem. The second problem is lines 249-250 with the default linker flag.

On second thought, I am confused with that script because I built with SDL2 but it still seemed to enable OpenGL support despite this setting here: https://github.com/gerstrong/Commander-Genius/blob/master/src/CMakeLists.txt#L6-L7

Is the intention to disable the OpenGL renderer if using SDL2? If so, it still seems to be working since that is the default render option in CGenius.cfg. So you maybe want to investigate that too, possibly making the default be OpenGL=false for the config file and/or ignoring that setting completely.

**Comment by gerstrong** [comment]
I have changed the file a bit. Can you let know if it works better now?

**Comment by clobber** [comment]
Well no, because you haven't addressed the main issue here which was the linker flag which will cause build failure on macOS: https://github.com/gerstrong/Commander-Genius/blob/master/src/CMakeLists.txt#L227-L229

I don't know how to state it more clearly than that. It needs to not be passed for APPLE targets and should probably only be LINUX.

Also, I'm still confused about the use of the OpenGL renderer if SDL2 is being used: https://github.com/gerstrong/Commander-Genius/blob/master/src/CMakeLists.txt#L6-L7

Could you please re-read my comment above yours and clarify on that?

**Pull request merged**
